name: ccic_record
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - xarray
  - cmocean
  - ca-certificates
  - openssl
  - jupyterlab
  - certifi
  - pip
  - pip:
    - ccic
    

