name: ccic_record
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - ca-certificates
  - cartopy
  - certifi
  - cmocean
  - cdsapi
  - dask
  - fsspec
  - h5netcdf
  - ipywidgets
  - jupyterlab
  - matplotlib
  - netCDF4
  - openssl
  - pip
  - python=3.10
  - s3fs
  - tqdm
  - xarray
  - scipy
  - pip:
    - ccic
